// Code generated by protoc-gen-go. DO NOT EDIT.
// source: caseylucas/third/v1/third_api.proto

package thirdv1

import (
	context "context"
	fmt "fmt"
	v1 "github.com/caseylucas/protobuf-second-go/second/v1"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPopularWidgetsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPopularWidgetsRequest) Reset()         { *m = GetPopularWidgetsRequest{} }
func (m *GetPopularWidgetsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPopularWidgetsRequest) ProtoMessage()    {}
func (*GetPopularWidgetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6860e32b5816641e, []int{0}
}

func (m *GetPopularWidgetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPopularWidgetsRequest.Unmarshal(m, b)
}
func (m *GetPopularWidgetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPopularWidgetsRequest.Marshal(b, m, deterministic)
}
func (m *GetPopularWidgetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPopularWidgetsRequest.Merge(m, src)
}
func (m *GetPopularWidgetsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPopularWidgetsRequest.Size(m)
}
func (m *GetPopularWidgetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPopularWidgetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPopularWidgetsRequest proto.InternalMessageInfo

type GetPopularWidgetsResponse struct {
	Widgets              []*v1.Widget `protobuf:"bytes,1,rep,name=widgets,proto3" json:"widgets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPopularWidgetsResponse) Reset()         { *m = GetPopularWidgetsResponse{} }
func (m *GetPopularWidgetsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPopularWidgetsResponse) ProtoMessage()    {}
func (*GetPopularWidgetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6860e32b5816641e, []int{1}
}

func (m *GetPopularWidgetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPopularWidgetsResponse.Unmarshal(m, b)
}
func (m *GetPopularWidgetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPopularWidgetsResponse.Marshal(b, m, deterministic)
}
func (m *GetPopularWidgetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPopularWidgetsResponse.Merge(m, src)
}
func (m *GetPopularWidgetsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPopularWidgetsResponse.Size(m)
}
func (m *GetPopularWidgetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPopularWidgetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPopularWidgetsResponse proto.InternalMessageInfo

func (m *GetPopularWidgetsResponse) GetWidgets() []*v1.Widget {
	if m != nil {
		return m.Widgets
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPopularWidgetsRequest)(nil), "caseylucas.third.v1.GetPopularWidgetsRequest")
	proto.RegisterType((*GetPopularWidgetsResponse)(nil), "caseylucas.third.v1.GetPopularWidgetsResponse")
}

func init() {
	proto.RegisterFile("caseylucas/third/v1/third_api.proto", fileDescriptor_6860e32b5816641e)
}

var fileDescriptor_6860e32b5816641e = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0x4e, 0x2c, 0x4e,
	0xad, 0xcc, 0x29, 0x4d, 0x4e, 0x2c, 0xd6, 0x2f, 0xc9, 0xc8, 0x2c, 0x4a, 0xd1, 0x2f, 0x33, 0x84,
	0x30, 0xe2, 0x13, 0x0b, 0x32, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84, 0x11, 0x8a, 0xf4,
	0xc0, 0x72, 0x7a, 0x65, 0x86, 0x52, 0x8a, 0x48, 0x3a, 0x8b, 0x53, 0x93, 0xf3, 0xf3, 0xc0, 0x5a,
	0xcb, 0x33, 0x53, 0xd2, 0x53, 0x4b, 0x20, 0xfa, 0x94, 0xa4, 0xb8, 0x24, 0xdc, 0x53, 0x4b, 0x02,
	0xf2, 0x0b, 0x4a, 0x73, 0x12, 0x8b, 0xc2, 0xc1, 0x32, 0xc5, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x4a, 0xc1, 0x5c, 0x92, 0x58, 0xe4, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xcc, 0xb8,
	0xd8, 0x21, 0x06, 0x15, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0xc9, 0xe8, 0x21, 0x39, 0x01,
	0x62, 0x9b, 0x5e, 0x99, 0xa1, 0x1e, 0x44, 0x5f, 0x10, 0x4c, 0xb1, 0x51, 0x1d, 0x17, 0x47, 0x08,
	0xc8, 0x7d, 0x8e, 0x01, 0x9e, 0x42, 0x45, 0x5c, 0x82, 0x18, 0x16, 0x08, 0xe9, 0xea, 0x61, 0xf1,
	0x8a, 0x1e, 0x2e, 0x47, 0x4a, 0xe9, 0x11, 0xab, 0x1c, 0xe2, 0x6e, 0xa7, 0x54, 0x2e, 0xf1, 0xe4,
	0xfc, 0x5c, 0x6c, 0x9a, 0x9c, 0x78, 0x21, 0x0e, 0x2b, 0xc8, 0x0c, 0x00, 0x05, 0x4d, 0x00, 0x63,
	0x14, 0x3b, 0x58, 0xaa, 0xcc, 0x70, 0x11, 0x13, 0xb3, 0x73, 0x48, 0xc4, 0x2a, 0x26, 0x61, 0x67,
	0x84, 0x2e, 0xb0, 0x5a, 0xbd, 0x30, 0xc3, 0x53, 0xc8, 0xa2, 0x31, 0x60, 0xd1, 0x98, 0x30, 0xc3,
	0x24, 0x36, 0x70, 0xf0, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xda, 0xbd, 0xd9, 0xbd,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ThirdAPIClient is the client API for ThirdAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ThirdAPIClient interface {
	// GetPopularWidgets returns popular widgets.
	GetPopularWidgets(ctx context.Context, in *GetPopularWidgetsRequest, opts ...grpc.CallOption) (*GetPopularWidgetsResponse, error)
}

type thirdAPIClient struct {
	cc *grpc.ClientConn
}

func NewThirdAPIClient(cc *grpc.ClientConn) ThirdAPIClient {
	return &thirdAPIClient{cc}
}

func (c *thirdAPIClient) GetPopularWidgets(ctx context.Context, in *GetPopularWidgetsRequest, opts ...grpc.CallOption) (*GetPopularWidgetsResponse, error) {
	out := new(GetPopularWidgetsResponse)
	err := c.cc.Invoke(ctx, "/caseylucas.third.v1.ThirdAPI/GetPopularWidgets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThirdAPIServer is the server API for ThirdAPI service.
type ThirdAPIServer interface {
	// GetPopularWidgets returns popular widgets.
	GetPopularWidgets(context.Context, *GetPopularWidgetsRequest) (*GetPopularWidgetsResponse, error)
}

func RegisterThirdAPIServer(s *grpc.Server, srv ThirdAPIServer) {
	s.RegisterService(&_ThirdAPI_serviceDesc, srv)
}

func _ThirdAPI_GetPopularWidgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularWidgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdAPIServer).GetPopularWidgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/caseylucas.third.v1.ThirdAPI/GetPopularWidgets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdAPIServer).GetPopularWidgets(ctx, req.(*GetPopularWidgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ThirdAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "caseylucas.third.v1.ThirdAPI",
	HandlerType: (*ThirdAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPopularWidgets",
			Handler:    _ThirdAPI_GetPopularWidgets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "caseylucas/third/v1/third_api.proto",
}
